CDH-53273: HDFS NN fails to start due to NoClassDefFoundError on SentryClientTransportConfigInterface
Change-Id: Id5b04bb9ce1c0e68cd593788e2f220ab257917e5
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/22220
Tested-by: Jenkins User
Reviewed-by: Alexander Kolbasov <akolb@cloudera.com>